### ISSUE TITLE
Project Feedback by Joseph

### ISSUE THREAD

**Issue by jmatembu** [NicholusMuwonge/Invento#3]
Hey @NicholusMuwonge 

Thank you for your time and effort that you put into the project. Here are my thoughts on the project.

## Generally
Overall, your implementation of the project is fair. It shows that you have knowledge on the basics of Laravel. I believe you can do more to contribute to projects.

## Pros
* Grouping of routes requiring same prefix and middleware.

## Cons
* Less than half of the project requirements were completed even with added time on project.
* No instruction for setting up the project since you took your own approach with Auth0
* Overlooking simplicity: Using Auth0 was an unnecessary overhead on the project. This must have taken much of your time needed towards the completeness of the project.
* No factories. Manually creating seed data in seeder files. This is an inflexible approach.
* Database structure brings complexity in recording service sales separate from item sales.
* Naming conventions not followed for models, tables, files etc. Causes unnecessary overrides.  `views/dashboard/saleEdit.blade.php` for example would rather be `views/sales/edit.blade.php`, `Servicing` model would rather be `Service` and `servicing` table would be `services`.
* No single test was written.

**Comment by NicholusMuwonge** [comment]
Thanks, @jmatembu, for this feedback I will make it a point to go ahead and practice more Laravel and in the process use the recommendations you just pointed out in the cons section.
